### ISSUE TITLE
NRPE Admin Interface

### ISSUE THREAD

**Issue by Tampa** [it-novum/openITCOCKPIT#980]
I have installed most systems with nrpe checking so the ability to interface with remote nrpe and change its config according to needs along with the ability to deploy new check plugins directly to those remote systems via an upload dialog and library on the monitor system.

Ability to deploy monitoring via nrpe directly to machines by suppling a sudo user key to the monitor system and letting it install nrpe and deploy configs directly to it, I suppose that would be the dream, but just deploying new configs and plugins would in itself reduce the work quite a bit.

**Comment by nook24** [comment]
Good idea. You could use an configuration tool like Ansible to query the openITCOCKPIT API/Database to get all hosts (or all hosts of an host group) and than run your playbook to deploy the Monitoring Agents on all hosts.

**Comment by Tampa** [comment]
I don't like Ansible and I meant more in the sense of  apt install openitcockpit-nrpe-handler -> configure to allow connection from monitoring host, let it generate a key, enter key in monitoring host.

Create new check command, as normal, new option underneath "use custom nrpe plugin", checked selects one of the available check plugins to deploy.

Under administration, check plugins, upload check plugin etc.

Bind to templates of course.

Could even spin it further setting up temporary keys for "setup" and have the host install nrpe and all required configs through temporary ssh connection. The whole point is to reduce deployment time of nrpe, because as is I have to install it, manually change its configs, put the plugins in, chmod them, bind the commands in nrpe config etc, it takes ten minutes per server, biggest order I had was 45+ servers, took two days to deploy.

**Comment by nook24** [comment]
We discussed your request and have decided not to implement it.

Here's why:
- There are lots of configuration management tools available (Ansible, Chef or Puppet just to name a few) that do a much better job than we could ever implement it.
- From the security's point of view, its a bit "insecure"

Our internal systems are using Ansible to deploy all monitoring related configs and tools on the target hosts. This is a snippet of one of our Ansible playbooks for example:
```yml
---
- hosts: all
  remote_user: vagrant
  vars_files:
    - vars/all.yml
    - vars/{{ ansible_distribution_release }}-special.yml
  roles:
    - server
    - docker
    - nginx
    - redis
    - monitoring # this is the NRPE and openITCOCKPIT API Part
    - systemutils
    - nfs
    - finish
```
